- hosts: all
  tasks:
    - name: Authenticate sudo for Homebrew installation
      ping:
      become: yes
  
    - name: Install Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
      args:
        creates: /usr/local/bin/brew

    - name: Clone Alfalfa
      git:
        repo: https://github.com/seattle-beach/alfalfa.git
        dest: ~/.alfalfa
        version: wip
        force: yes

    - name: Clean up existing config files
      command: mv {{ item }} {{ item }}.orig
      args:
        creates: "{{ item }}.orig"
      with_items:
        - ~/.bash_profile

    - name: Symlink config files
      file: src=~/.alfalfa/dotfiles/{{ item.key }} dest={{ item.value }} state=link
      with_dict:
        .bash_it: ~/.bash_it
        .bash_profile: ~/.bash_profile
        .git-authors: ~/.git-authors
        .git-authors: ~/.pairs
        .gitconfig: ~/.gitconfig
        .gitignore_global: ~/.gitignore_global

    - name: Tap Homebrew repositories
      homebrew_tap: tap={{ item }}
      with_items:
        - caskroom/fonts
        - git-duet/tap
        - pivotal/tap

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Install Homebrew formulae
      homebrew: name={{ item }}
      with_items:
        - direnv
        - git-duet
        - git-pair

    - name: Install Homebrew casks
      homebrew_cask: name={{ item }}
      with_items:
        - font-hack
        - font-source-code-pro
        - iterm2
        - macvim
        - shiftit

    - name: Update OS X defaults
      osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }}
      with_items:
        - domain: com.apple.Terminal
          key: Default Window Settings
          type: string
          value: Pro
        - domain: com.apple.Terminal
          key: Startup Window Settings
          type: string
          value: Pro

    - name: Create ~/workspace
      file: path=~/workspace state=directory
