- hosts: all
  tasks:
    - name: Authenticate sudo for Homebrew installation
      ping:
      become: yes
  
    - name: Install Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null
      args:
        creates: /usr/local/bin/brew

    - name: Clone Alfalfa
      git:
        repo: https://github.com/seattle-beach/alfalfa.git
        dest: ~/.alfalfa
        version: wip
        force: yes

    - name: Clean up existing config files
      command: mv {{ item }} {{ item }}.orig
      args:
        creates: "{{ item }}.orig"
      with_items:
        - ~/.bash_profile

    - name: Symlink config files
      file: src=~/.alfalfa/dotfiles/{{ item.src }} dest={{ item.dest }} state=link
      with_items:
        - { src: .bash_it, dest: ~/.bash_it }
        - { src: .bash_profile, dest: ~/.bash_profile }
        - { src: .gemrc, dest: ~/.gemrc }
        - { src: .git-authors, dest: ~/.git-authors }
        - { src: .git-authors, dest: ~/.pairs }
        - { src: .gitconfig, dest: ~/.gitconfig }
        - { src: .gitignore_global, dest: ~/.gitignore_global }

    - name: Tap Homebrew repositories
      homebrew_tap: tap={{ item }}
      with_items:
        - caskroom/fonts
        - git-duet/tap
        - pivotal/tap

    - name: Update Homebrew
      homebrew: update_homebrew=yes

    - name: Install Homebrew formulae
      homebrew: name={{ item }}
      with_items:
        - direnv
        - git-duet
        - git-pair
        - postgresql
        - rbenv
        - ruby-build

    - name: Install Homebrew casks
      homebrew_cask: name={{ item }}
      with_items:
        - font-hack
        - font-source-code-pro
        - iterm2
        - macvim
        - shiftit

    - name: Update OS X defaults
      osx_defaults: domain={{ item.domain }} key={{ item.key }} type={{ item.type }} value={{ item.value }}
      with_items:
        - domain: com.apple.Terminal
          key: Default Window Settings
          type: string
          value: Pro
        - domain: com.apple.Terminal
          key: Startup Window Settings
          type: string
          value: Pro

    - name: Create ~/workspace
      file: path=~/workspace state=directory

    - name: Create LaunchAgents dir
      file: path=~/Library/LaunchAgents state=directory
    - name: Get Postgres launch agents
      shell: ls /usr/local/opt/postgresql/*.plist
      register: postgres_launch_agents
    - name: Link Postgres launch agents
      file: src={{ item }} dest=~/Library/LaunchAgents/{{ item | basename }} state=link
      with_items: "{{ postgres_launch_agents.stdout_lines }}"

    - name: Install Ruby 2.2.4
      command: /usr/local/bin/rbenv install 2.2.4

    - name: Install Ruby gems
      command: /usr/local/bin/gem install bundler
